/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(data_distributor.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(dd57b10ab717c81b895e2330b9f247e3)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnss/data_distributor.h>
// pydoc.h is automatically generated in the build directory
#include <data_distributor_pydoc.h>

void bind_data_distributor(py::module &m) {

  using data_distributor = gr::gnss::data_distributor;

  py::class_<data_distributor, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<data_distributor>>(m, "data_distributor", D(data_distributor))

      .def(py::init(&data_distributor::make), py::arg("numSamples"), D(data_distributor, make))

      ;
}
