/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(decimator.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(1a72ccc37ec7582139920d84cef2cb71)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnss/decimator.h>
// pydoc.h is automatically generated in the build directory
#include <decimator_pydoc.h>

void bind_decimator(py::module &m) {

  using decimator = gr::gnss::decimator;

  py::class_<decimator, gr::sync_decimator, std::shared_ptr<decimator>>(m, "decimator",
                                                                        D(decimator))

      .def(py::init(&decimator::make), py::arg("sample_freq"), D(decimator, make))

      ;
}
