/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(tracking_ff.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(a97eb98258edcfd18552e0ca3b3d3d48)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnss/tracking_ff.h>
// pydoc.h is automatically generated in the build directory
#include <tracking_ff_pydoc.h>

void bind_tracking_ff(py::module &m) {

  using tracking_ff = gr::gnss::tracking_ff;

  py::class_<tracking_ff, gr::sync_block, gr::block, gr::basic_block, std::shared_ptr<tracking_ff>>(
      m, "tracking_ff", D(tracking_ff))

      .def(py::init(&tracking_ff::make), py::arg("_channelNum"), py::arg("_sampleFreq"),
           py::arg("pll_nbw"), py::arg("pll_dr"), py::arg("pll_lg"), py::arg("dll_nbw"),
           py::arg("dll_dr"), py::arg("dll_lg"), D(tracking_ff, make))

      ;
}